## This is test deployment for Kubernetes platforms.
## This is not intended to be used in production.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-codeigniter
  name: test-codeigniter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-codeigniter
  template:
    metadata:
      labels:
        app: test-codeigniter
    spec:
      containers:
      - image: bitnami/codeigniter
        name: codeigniter
